### ISSUE TITLE
Using reverse ETL for marketing

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#11]

**Comment by krevitt** [comment]
Draft:
https://docs.google.com/document/d/16da097qjEn3hCNzcDnwzw1akc0S5dZqZUuTbNV303xQ/edit

**Comment by krevitt** [comment]
Going to structure as two separate posts:
- userflow + segmentation of messaging for relevance
- another for internal tooling + tracking manually-set goals vs actuals

**Comment by gwenwindflower** [comment]
transferred to this discussion https://github.com/dbt-labs/docs.getdbt.com/discussions/1149
