### ISSUE TITLE
You built a dashboard, now what?  A case for Frameworks

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#13]
Most orgs have an ever-growing list of dashboards where they've drawn some insights/analyses on, but how is this documented? How do we know when to deprecate the dashboard? How do we consolidate all of this knowledge?
Andrew came up with the idea of having analytics frameworks. They're evergreen resources on areas of the business and document all dashboards/analyses/metric definitions. This will be a case for why you should use an analytics framework when you begin building dashboards

**Comment by krevitt** [comment]
@aescay is this still something you're interested in writing?  launch of the devhub blog is coming up on 11/29, let us know if you'd like to:

a) write this and publish at launch
b) write this sometime later
c) not write this at all!

**Comment by aescay** [comment]
Yes 💯  still up for writing this. I was supposed to throw an outline here last week but fell behind on this. Will work to get an outline out in the next couple of days. Does that still line up well with the release schedule?

**Comment by krevitt** [comment]
Glorious, yes that'd work well

**Comment by gwenwindflower** [comment]
feels like we have low capacity/appetite to tackle this right now, going to close this and we'll see if it bubbles back up at some point
