### ISSUE TITLE
Guide to working with unstructured data - part 1

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#14]
Sanjana is putting together a series of posts on introducing new data practitioners to unstructured data. This will be a three part post.
Part 1 - What is unstructured data?
Part 2 - How to work with unstructured data in sql
Part 3 - How to work with unstructured data in dbt

**Comment by gwenwindflower** [comment]
feels like this one never took off so going to close for now, i have no doubt we can get some _excellent_ teaching from the community on this in the near future
