### ISSUE TITLE
A case for self-service: how to build a symbiotic relationship between data practitioners and stakeholders

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#16]
Brandon has done a fantastic job bridging the gap between data practitioners and stakeholders. This topic will be a validation of how GOOD someone (who is not a data team memebr) can get when they have the time to go very deep on their analytical area of expertise.

**Comment by gwenwindflower** [comment]
Per the other Data team pieces that haven't had movement, it doesn't seem like they have capacity to spare right now so we can shut these down and see if they come back around in the future
