### ISSUE TITLE
Airflow with dbt Core & Cloud

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#2]
Based on Sung's meetup talk, ([replay here](https://www.youtube.com/watch?vn7IIThR8hGk), [slides here](https://drive.google.com/file/d/1P9a5mafm3g0szpFLfIB2hMOnIjL5aPKL/view))

Draft here in docs here:
https://docs.google.com/document/d/12dcgxPr1GYQkPzVHDxiK8wF7GR2Iu150HP1YB2R1uRE/edit

Next step - blend in key points from:
Snaptravel's Coalesce talk last year: https://www.youtube.com/watch?vZ6dPIXGj29M
Kenny's airflow deployment draft here: https://docs.google.com/document/d/1Dsv7HPQ3GnahCu2JMNAAI9N6YWZSfQGatQvGVi3EyXs/edit#

**Comment by krevitt** [comment]
Main thing to discuss on 11/18: 
- personal stories of implementations (whether from your consulting days or dbt customers, company-anonymous of course) that went well / not so well
- including background on team structure / timeline, to weave into the broader team structure / timeline framing from your talk

**Comment by krevitt** [comment]
@sungchun12 spice 🌶️ has been applied!  see a [2nd draft here ](https://docs.google.com/document/d/12dcgxPr1GYQkPzVHDxiK8wF7GR2Iu150HP1YB2R1uRE/edit#bookmark=id.e1ov4gxlmdxo) at the 'rewrite with spice' bookmark.

this is a *very* different post than your original presentation, curious to hear your thoughts - are there pieces from the original draft that we'd want to pull in here?  anything that we're missing?

**Comment by sungchun12** [comment]
@krevitt I added suggestions and comments in the google doc. I love the 2nd draft compared to the first. The evolving story makes the tech mentioned feel like realistic choices rather than buzzwords and tools being thrown around. 

The rewrite does a good job of centering the people/process problems rather than going into a feature battle across the tech.

**Comment by krevitt** [comment]
Love it, thanks Sung - think this one's good to ship!
