### ISSUE TITLE
Model Naming Conventions Part 1: On the Importance of Naming

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#21]
@patkearns10  put together an excellent [post](https://www.notion.so/dbtlabs/Model-Naming-Conventions-d4d7d6ef284545d9827836662f7ab01f) on naming conventions. 

This will be a great candidate for an early piece on DevHub post launch.

**Comment by jasnonaz** [comment]
Changing the name to reflect our discussion on [slack](https://dbt-labs.slack.com/archives/C02G5V9JBHV/p1637089379140100?thread_ts=1636597646.120100&cid=C02G5V9JBHV) that this is now going to be a multi parter. 

@patkearns10  - I've pulled the first section into a [new doc](https://docs.google.com/document/d/1gMtdBZMc3aU5KnY7srrc1seXMGaMHoABMgnxSdm-4mQ/edit#). Want to go over the edits then we can work on getting this finalized and ready to go?

**Comment by jasnonaz** [comment]
@patkearns10 just did a final runthrough on the wording and added a few final tweaks - take a look and I think we should be good to go!

**Comment by patkearns10** [comment]
@jasnonaz -- all set on your tweaks. I have one added paragraph from Friday assigned to you. Resolve it if we are good to go!
