### ISSUE TITLE
Adding dbt Cloud to your existing dbt Core setup

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/dbt-technical-blog-writing#28]
I don't know if this is a blog post or not but this is a question that I get quite a bit with consulting partners who don't understand what the lift looks like coming from dbt core to adding dbt Cloud.

**Comment by jasnonaz** [comment]
@amychen1776 are you planning on taking this or should we open this up and add the 'looking for author' tag to see if we can start getting folks in on this.

**Comment by amychen1776** [comment]
@jasnonaz I actually think this would be a great one to pair with someone external, perhaps a customer or consulting partner. Let me check to see if anyone is interested.

**Comment by amychen1776** [comment]
@jasnonaz 

@anaisvaillant is going to write this! 🥂 I'll be riding aside to help if desired :)

**Comment by jasnonaz** [comment]
Fantastic!! Got this all noted down - looking forward to reading @anaisvaillant.

**Comment by anaisvaillant** [comment]
excited for this one! thanks for including me @amychen1776

**Comment by gwenwindflower** [comment]
seems like this has gone kind of stale, but really important guide for us to create. linking through to this discussion. https://github.com/dbt-labs/docs.getdbt.com/discussions/1160
