### ISSUE TITLE
Stages of dbt project maturity

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#29]
Based on @dave-connors-3's upcoming Coalesce talk and the accompanying repo [https://github.com/dbt-labs/dbt-project-maturity](https://github.com/dbt-labs/dbt-project-maturity)

Publish as a blog post to be released along with the talk, Dave C to work with Ganz / Krevitt to publish after talk deck/notes/replay are ready.

**Comment by dave-connors-3** [comment]
some resources i am developing

- [blog post draft](https://docs.google.com/document/d/1oAXcopSBz7HUjGoiAaowxSdAhGX8JrEe5PshKz6y6jE/edit) (very WIP)
- [slide deck draft](https://docs.google.com/presentation/d/106XFnuv1du4wtUKotNuVwAdQuzsMD55XO9hz-td5Vew/edit#slide=id.gfb4b150fbc_0_27) (WIp)
- [zoom recording from first runthrough](https://dbtlabs.zoom.us/rec/share/JXK9LL70agJW4Sj3g8lhg1DLJ3RFQVMi5s465fQYWNOyc-SkzUed2JlMYu58xZnb.tchvQA2wsWcA8iK7?startTime=1635448145000) (feat. @aescay)

**Comment by krevitt** [comment]
this is awesome @dave-connors-3 - curious if there are specific pieces you'd like help polishing in the post?  think pulling in some of the graphics from your deck would be great

**Comment by dave-connors-3** [comment]
@krevitt i would definitely appreciate some copy editing on the blog draft -- there's no reason for it to be 7 pages long -- it was written mostly stream of conciousness as i was running through the deck, so I guarantee there's repetition and just flat out bad sentences in there. And i agree the visuals would help! which do you think are most impactful so far?
