### ISSUE TITLE
Lessons you learn as a head of data & CEO 

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#30]
Tristan's initial post on DevHub:

There are very few people in the world that have run data teams in the modern data stack and been the CEO of a hypergrowth tech company.

What if write a post that gives lessons bidirectionally:
Give some lessons to data teams on how to work with / interact with CEOs
Give some lessons to CEOs on how to work with / interact with their data teams.

**Comment by gwenwindflower** [comment]
@jasnonaz is this still something we want to do or are we good to close for now?

**Comment by gwenwindflower** [comment]
closing for now but plan to circle back to this at the right time
