### ISSUE TITLE
How to clean up your workspace

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-technical-blog-writing#31]
In ProServ engagements, sometimes clients are apprehensive about dbt creating a bunch of dev schemas in their warehouse and muddying the waters.  Clients are always stoked when I give them a macro to clean those up.  I've seen a couple macros for going into snowflake and dropping unused schemas (developer no longer employed, models that are no longer active, etc) lying around which I collected here a while back: https://github.com/patkearns10/dbt_workspace/tree/master/dbt/macros/snowflake_utils/cleanup

We can definitely tell other people these exist
- I'm sure most people (?) know how to go into snowflake and drop deprecated tables manually
- Maybe some people know how to drop a whole schema
- Most people probably do not know that you can run an operation from dbt to drop dbt related schemas (or any / all schemas) or drop objects that are older than X days, etc. 

Maybe we could formalize these into more approved versions and add to `dbt_utils`?

**Comment by jasnonaz** [comment]
@patkearns10 what do we think - this next up on deck or part 2 of model naming conventions?

**Comment by patkearns10** [comment]
Model naming conventions!  I will need to build a bunch of things for this one, which will be more difficult for me at the moment.
