### ISSUE TITLE
Leveraging surrogate keys so that every model has a primary key

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#34]
@sanjanasen96 put together some great reasoning on using surrogate keys for all your models to create primary keys.  Would love to leverage this existing thinking in devhub!

resources:
- [wistia link](https://getdbt.wistia.com/medias/anuo7x4w3a)
- [script link](https://docs.google.com/document/d/1nxj5voDt2TPEHfsqZTdfuh0A4QoG54bnQSsC8JHBz9A/edit?usp=sharing)

**Comment by krevitt** [comment]
Draft ready here: 
https://docs.google.com/document/d/1P8R44U2fsu5CIItKFgXaqksWokW4Bs1igLjeeP5NPeY/edit#

Think this makes a nice little SQL magic post!

**Comment by krevitt** [comment]
@sanjanasen96 realized we never tagged you on this surrogate keys post (which ties in closely to the other PK testing post) - want to give this a read when you have a min?

**Comment by sanjanasen96** [comment]
@krevitt @jasnonaz Read this, letting you know that I actually have no comments! Great article!
