### ISSUE TITLE
The importance of testing your primary keys

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#35]
@sanjanasen96 created another excellent resource for why it is important to test your primary keys.  Checkout the resources below:

resources:
- [wistia link](https://getdbt.wistia.com/medias/hnkw6j7m2t)
- [script](https://docs.google.com/document/d/15LzaMBV5rcAA5VwZpYQFf79K03k40q9jTEsU6hpLg1o/edit?usp=sharing)

**Comment by krevitt** [comment]
@sanjanasen96 Ganz and I wrote up a post based on your primary key testing training vid, want to give it a read sometime this week and let us know what you think?  

happy to share the byline together, have you own the byline (or be completely off the byline!), totally up to you.

https://docs.google.com/document/d/1kfcBVBy7u3jToyZstx72bzl2DWQCKuMefZj3LNx5TME/edit#

**Comment by sanjanasen96** [comment]
@krevitt @jasnonaz left a v1 review!
