### ISSUE TITLE
Setting up bigquery to get started with dbt

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#39]
This post would be a stable guide for getting the minimum effective set up on BigQuery to start using dbt. This would support any developer who is:
- setting up dbt with BigQuery
- completing the GS tutorial
- learning on courses.getdbt.com

**Comment by patkearns10** [comment]
First pass at this using screenshots:
https://docs.google.com/document/d/19MoprJZs5TVFwzemqUOTJ7P0Q1iJdbCNu1iJ5w6FFp4/edit#

**Comment by krevitt** [comment]
@coapacetic @runleonarun curious where we think the "how we configure" piece (as in jerco's [snowflake post](https://blog.getdbt.com/how-we-configure-snowflake/), covering connections / databases / warehouses / roles / users) fits in here - separate post for each warehouse?

**Comment by patkearns10** [comment]
> @coapacetic @runleonarun curious where we think the "how we configure" piece (as in jerco's [snowflake post](https://blog.getdbt.com/how-we-configure-snowflake/), covering connections / databases / warehouses / roles / users) fits in here - separate post for each warehouse?

I am curious about that too -- configuring could be done in my post and I started to do a bare minimum, without going into any detail of why.

Also could spend more time talking about Amy Chen's diagram  talking about naming convention changes between warehouses
 ![Screen Shot 2022-01-07 at 7 34 00 AM](https://user-images.githubusercontent.com/30663534/148448046-0c025368-5da0-4142-b087-635f7436f28c.png)
Could be neat to have a snippet that fits into multiple posts that we can change in one place

**Comment by amychen1776** [comment]
@patkearns10 as a heads up, I finally updated that diagram because of a typo (and Databricks making it far too confusing). 
![image](https://user-images.githubusercontent.com/46451573/148555217-44e29449-f7ba-4094-b345-ab29a0b34f4d.png)

**Comment by patkearns10** [comment]
> @patkearns10 as a heads up, I finally updated that diagram 
Yes, that's why I added "Not Final" over it at the bottom of the image :)

**Comment by amychen1776** [comment]
Lol I didn't see that in my little preview. Thanks! I'm adding more to it as I get the information :)

**Comment by jasnonaz** [comment]
This is awesome - glad we got this going, thank you everyone. I'm going to close this out since it won't be living on the dev blog + the discussion is now happening over in the docs pr.
