### ISSUE TITLE
How to use dbt-labs docker image of dbt

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#40]
**What's your key point?**
Developers are interested in using the [dbt-labs docker image](https://hub.docker.com/r/fishtownanalytics/dbt) for dbt. It would be great to have a single post in devhub for how to get started with this.  

**Prior art:**
I wasn't able to find much on using this docker image specifically.  I did some searching on Google and dbt slack, but couldn't find anything specific.

Edward and Sandeep both raised this idea in the [#learn-on-demand channel](https://getdbt.slack.com/archives/C01DU491K1A/p1635351975010100) and the docker hub page linked above doesn't have strong documentation.

**Link to notes / draft:**
Started a blank document here for getting started: https://docs.google.com/document/d/1nKpOOOTDvlNu53h9v3MzrmeMXQEq7XDxgATq_9Vm8Xc/edit?usp=sharing

**Any open questions / requests for help from the group?**
I'm not an expert in docker (yet!) but would love to pair with someone more experienced to build this.

**Comment by jasnonaz** [comment]
Todo: Check if anyone on the Core team is interested in taking this

**Comment by gwenwindflower** [comment]
closing as we're going to improve these docs https://github.com/dbt-labs/docs.getdbt.com/issues/1028
