### ISSUE TITLE
[NEW] How to safely snapshot modelled data

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-technical-blog-writing#41]
**What's your key point?**
- When should you? Ways to avoid it
- Considerations for backfill as it changes

**Prior art:**
The opposite to all of our snapshot writing ever

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

**Any open questions / requests for help from the group?**
- Should you snapshot or make an incremental model with the date as part of key? Feels like space constraints (Redshift) vs ergonomics bc it's nice to have a pre-spined table

**Comment by jasnonaz** [comment]
@joellabes you gonna take this one or should we open up to the crowd?

**Comment by joellabes** [comment]
Yeah I'd like to have a swing at this one! 

#2022YearOfTheSnapshot

**Comment by gwenwindflower** [comment]
closing this one, we're touching on similar topics with some of the content currently in editorial, and i've got a related piece i spiked out earlier this week which i'll add as a discussion in the docs repo -- this will definitely resurface if needed!
