### ISSUE TITLE
[NEW] How to install python and dbt in a venv on an intel mac without losing your mind

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-technical-blog-writing#42]
**What's your key point?**
Python bad. 

**Prior art:**
https://docs.getdbt.com/dbt-cli/installation#pip

**Link to notes / draft:**
[How to get your python going on Mac.txt](https://github.com/dbt-labs/devhub-writing/files/7437767/How.to.get.your.python.going.on.Mac.txt)

Maybe this should be part of the docs instead of DevHub? @jasnonaz please advise. @VersusFacit is going to write this up from the notes of our call 💜

**Comment by amychen1776** [comment]
@joellabes Could we include M1 macs because....that's been a hell fest recently.

**Comment by joellabes** [comment]
💯 yes yes yes
