### ISSUE TITLE
How to think about environments in dbt

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/dbt-technical-blog-writing#43]
**What's your key point?**

A common question that gets asked in the enterprise space and in the #dbt-cloud channel in slack is centered around how to set up their environments and dbt Cloud projects, especially when they have multiple BQ projects or Snowflake accounts/defined environments 

Update: I think I have a different post in mind to expand this and meet an need that I keep seeing about just how to think about environments. 

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*

[A work in progress for 1+ years](https://docs.google.com/document/d/1yklL5Gdn9c7gP7Jj-NCEdCT61w_kTxHeWyWKcoz0QxU/edit?disco=AAAAHzaxC7E&usp_dm=false)

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
https://docs.google.com/document/d/1CDcO_8vKs9KfDtn1lJ5vFw2xqxGB7hq5Jmbd3C5PbQE/edit#heading=h.e43pwkaqj731

**Any open questions / requests for help from the group?**

**Comment by amychen1776** [comment]
Here is the general outline that I have for this blog post:

- why should you care about environments
- what could an environment mean in dbt (the people, git repo, data platform, dbt project)
- what you need to set up your environment (in git, on the data platform, dbt project, dbt cloud project).

**Comment by gwenwindflower** [comment]
transferred here https://github.com/dbt-labs/docs.getdbt.com/discussions/1146
