### ISSUE TITLE
Using dbt and BigQuery to study developer community growth

### ISSUE THREAD

**Issue by rossturk** [dbt-labs/dbt-technical-blog-writing#45]
**What's your key point?**

Using dbt, it is easy to create a simple metrics pipeline for studying the behavior of developer communities.

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*

I am not aware of any prior art.

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

https://docs.google.com/document/d/1O9dLtaGc8pHhBjaJjQ3eKUptGEidZOwSh3Fz8bV6va4

**Any open questions / requests for help from the group?**

**Comment by krevitt** [comment]
@rossturk gave it a full readthrough - the detail-oriented steps are excellent.  like I mentioned, you can drop images etc inline in the doc and we'll get them into the blog post.

one thing that your colleagues called out - some stories would really help set the stage here!  i wonder if you could open with a beefier storytelling section (how you data like this to drive decision-making there, examples of decisions you've made and their impact) to hook readers, before getting into the technical details.

**Comment by rossturk** [comment]
@krevitt I was worried about it getting too long, which is why the intro and final section are a bit brief. I'll stop worrying about that and go to town.

**Comment by rossturk** [comment]
@krevitt I have made a bunch of changes, expanding the intro and conclusion sections. Let me know what you think!

**Comment by krevitt** [comment]
@rossturk left a bunch of comments, mostly confirming that changes you made are super helpful.  think this is very closely to ready to ship.

the two final things that I think could improve:
- the opening sentence (could use a hook that matches more with the spirit of what the article's become)
- the close once you have superset configured (what'd you learn / what are you curious to explore now that you have it built?)
