### ISSUE TITLE
Using GitHub actions and the Cloud API to load artifacts to your DWH 

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-technical-blog-writing#46]
**What's your key point?**
Claire wrote about Snowflake's [PUT action here](https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214). With the inbuilt performance analysis, _this specific_ use case is no longer necessary, but there's still times when people want to have access to their old artifacts. 

[Mirna and Randy suggest](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1636042506172700) using the dbt Cloud API

It'd be cool if we could build a template GH action that people can copy and just put in their dbt Cloud API key and S3 key. Easy mode is just running on a schedule, hard mode would involve invoking on every run somehow...

**Prior art:**
https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214
https://dbt-labs.slack.com/archives/C017GDLAF7D/p1636042506172700

**Comment by jasnonaz** [comment]
@joellabes you interested in taking this one or should we start shopping around?

**Comment by joellabes** [comment]
Happy for someone else to do this one!

**Comment by gwenwindflower** [comment]
i think we should let this one resurface if needed, closing for now
