### ISSUE TITLE
UX design: the key to becoming a full-stack data analyst

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#48]
**What's your key point?**
It makes me wonder - why within the field of data, is design thinking often so absent? In order to realize the full potential of the “full stack analyst”, we must apply the principles of design to be part of our workflows. We should shift our thinking from making traditional dashboards to building user-centric analytical applications.

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
Not sure!  Seth can edit.

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
https://docs.google.com/document/d/11O_5il5ytrL-4cBZqB5ca3rv-7wNbjshTLYKusUCu94/edit

**Any open questions / requests for help from the group?**

**Comment by sethdr** [comment]
A couple articles I link to regarding "prior art"

https://locallyoptimistic.com/post/run-your-data-team-like-a-product-team/
https://locallyoptimistic.com/post/user-research-for-data-part-1/
https://roundup.getdbt.com/p/seth-rosen-topcoat

**Comment by sethdr** [comment]
This is ready for review. Happy to continue making changes: https://docs.google.com/document/d/11O_5il5ytrL-4cBZqB5ca3rv-7wNbjshTLYKusUCu94/edit

**Comment by krevitt** [comment]
@sethdr i got out the red pen and [suggested a bunch of edits](https://docs.google.com/document/d/11O_5il5ytrL-4cBZqB5ca3rv-7wNbjshTLYKusUCu94/edit#) - mostly condensing sections and moving things around to enhance the flow, didn't really write many net-new words.  

with the do/don't tables in here now, i think this serves the goal of a bookmark-able post for analysts to return to, without being too dense.

lemme know if this is good to publish!
