### ISSUE TITLE
dbt Product emails as blog posts

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#50]
**What's your key point?**

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
https://www.notion.so/dbtlabs/HTML-for-Product-Update-Emails-58915eea59304212a223a5896ed831cd

**Comment by krevitt** [comment]
@CraiFish added the most recent 3 product update emails ([deploy preview here](https://deploy-preview-808--docs-getdbt-com.netlify.app/blog/tags/dbt-updates)).  

want to take a look and lmk if these look good?  probably won't have time to add the rest of the back catalog for launch, but at least wanted to get a few in there.

**Comment by CraiFish** [comment]
I assume it's not easy to begin the preview for each at "What's new"? Since my opener is always pretty topical? If that assumption is correct then it looks good!

**Comment by krevitt** [comment]
yep you assumed correctly, we can basically just set a `truncate` point at some point after the beginning of the blog (but can't set it to be from the middle of the post).
