### ISSUE TITLE
Measuring Business Hours

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-technical-blog-writing#51]
**What's your key point?**

How to measure business hours for SLA metrics! this can be a really complex thing to capture the actual amount of time that tasks in a service desk style process take

**Prior art:**
Many conversations on Slack 😅 

**Link to notes / draft:**
[Version 1](https://github.com/dbt-labs/internal-analytics/pull/253) (dbt Labs only link for now)
[Version 2 (never implemented)](https://github.com/fishtown-analytics/dbt-labs-experimental-features/pull/13/commits/db0b5c5ec9482a1ddafae1e89a638999c4811ebb)
[Version 3](https://github.com/dbt-labs/internal-analytics/pull/622) (dbt Labs only link for now)

[Blog Draft](https://docs.google.com/document/d/1zeSL1qfNGCo2Zd6Wns7idOj3p16durOpBkoRvXFA6SU/edit?usp=sharing)

**Any open questions / requests for help from the group?**

**Comment by jasnonaz** [comment]
Fantastic stuff here Dave. Thanks for putting this together - I'll have edits back to you by next Tuesday and we can plan for an early January Launch.

**Comment by dave-connors-3** [comment]
@jasnonaz I just did a small round of edits here myself, and sent it over to @ericalouie to give it her blessing since we collab'd a bit. Would love to connect this week on this! #devhub5ever

**Comment by jasnonaz** [comment]
Awesome. This piece is super strong. It does a fantastic job bringing the practical technical implementation alongside a measured assessment of when and how to use this metric. I had some light comments to address within, once those are addressed we should be ready to launch this.

**Comment by jasnonaz** [comment]
We're live!! Thanks Dave https://docs.getdbt.com/blog/measuring-business-hours-sql-time-on-task
