### ISSUE TITLE
dbt Fundamentals v2 launch post

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#52]
**What's your key point?**

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

**Any open questions / requests for help from the group?**

**Comment by jasnonaz** [comment]
@alexiswo is interested in potentially doing a deeper dive into how / why we made v2 - lets open up a new issues for that since this was about the initial announcement post which went up on main blog
