### ISSUE TITLE
A Guided Tour of Your dbt Project

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#6]
A granular look at the folders and areas within a dbt project to demystifying what can be a confusing process of first seeing macro / model / seed / target etc etc and not knowing what is what

**Comment by krevitt** [comment]
@jasnonaz Amy Chen has a video walkthrough of this already - starting at 5mins here: https://getdbt.wistia.com/medias/q0xm7mdt61

this could be a good starting point, but this also seems like a DX-owned post yeah (being so fundamental + something we'll want to keep updated)?

**Comment by gwenwindflower** [comment]
i'm going to close this one for now, but feel free to open a fresh discussion in the docs repo if you feel strongly about it!
