### ISSUE TITLE
Allowing Restricted IP Access to Redshift from dbt Cloud 

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/dbt-technical-blog-writing#60]
I wrote this up in discourse: https://discourse.getdbt.com/t/allowing-restricted-ip-access-to-redshift-from-dbt-cloud/3446

And there was a brief discussion about where it could live: https://dbt-labs.slack.com/archives/C02HE19D51R/p1638541826156000

Thank you!

**Comment by gwenwindflower** [comment]
we will loop back to this when we mass port a selection of discourse posts into the blog. closing for now, thank you!
