### ISSUE TITLE
Writing & debugging Jinja Macros

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-technical-blog-writing#61]
**What's your key point?**
Do we have any best practice recommendations around testing macros / jinja code?
Slack convo: https://dbt-labs.slack.com/archives/C0186FAQTMF/p1638903594083500

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
- coalesce talk: Lewis Davies & Erika Pullum (The Call is Coming from Inside the Warehouse: Surviving Schema Changes with Automation)
- https://getdbt.slack.com/archives/C02DGKES4Q0 (
- https://getdbt.slack.com/archives/C02DGKES4Q0/p1638906527053300
- 

**Link to notes / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

**Any open questions / requests for help from the group?**

**Comment by krevitt** [comment]
Adding @dave-connors-3 and @coapacetic here

**Comment by gwenwindflower** [comment]
closing for now, we have a pretty good slate of stuff ported to the new repo and/or stuff in progress so dropping remaining ideas that haven't progressed
