### ISSUE TITLE
Optimizing dbt Models with Redshift

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/dbt-technical-blog-writing#65]
### Discussed in https://github.com/dbt-labs/dbt-technical-blog-writing/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **christineberger** December  3, 2021</sup>
Redshift's ability to tweak how you can sort and distribute data across nodes gives Redshift users a unique position to tune up their transformation flows with dbt. When following some best practices, we can effectively reduce run times (the best one I've done is from 7+ hours to ~3 hours just with some model refactoring, sort, and distribution strategies!)

Sort and distribution can sound scary, and to be honest, many Redshift users _know_ about them but up until implementing dbt, it was hard to take the time to figure out how to implement them in a meaningful way. With dbt, that's changed -  dbt makes it easy to see how your data relates and the insight you get from this is advantageous when mapping out your sort and dist configs. 

With this write up I will explain what each configuration means and what benefits they have to the database, as well as how you should architect your dbt models to get the best out of these configurations.</div>

**Comment by krevitt** [comment]
Notes: potentially to include in a Redshift + dbt whitepaper, can probably stand alone as its own dev blog post as well.

**Comment by amychen1776** [comment]
@krevitt We are already in talks with Redshift to write this whitepaper. The goal is to start writing it in January. It will definitely take time to do some more research because I need to push and see what the line is for Serverless/RA3 node recommendations too.

**Comment by gwenwindflower** [comment]
per amy's comment i'm closing this one and not porting it

**Comment by christineberger** [comment]
@dbt-labs/devhub This was closed, but there was additional conversation that happened outside of this. @amychen1776, tagging you here so we can look at this again, as I have a [more complete version of this](https://www.notion.so/dbtlabs/Redshift-Optimization-with-dbt-3a9c46a0b84c462ebc8a188c562b3499) now. We'd talked about keeping it as separate things, but would love a re-assessment from you particularly on whether you think this is still relevant based on all the things we talked about in our call!

**Comment by krevitt** [comment]
This would be an absurdly excellent dev blog post Christine - given it's redshift-specific, feel like a blog post is the right spot for it (vs a guide, where we'd expect to have coverage of ~all warehouses).  

Curious what you think @amychen1776 re how this should be published.

**Comment by amychen1776** [comment]
@krevitt @christineberger I think we should go ahead and post this as a blog post. We are currently in the works with Redshift to create a Redshift best practices whitepaper that we will likely incorporate things from this post to it. But let's keep it short and sweet and easily sharable in this format :)
