### ISSUE TITLE
[NEW] Astronomer + dbt 

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/dbt-technical-blog-writing#66]
**What's your key point?**

This is a potential for the devhub but Astronomer is releasing their provider that will support dbt Core & cloud + Airflow. Until the post is written, it is a little up in the air on where this will be published. 

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*

**Link to notes / outline / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

**Estimated first draft date:**
*Leave blank if you already shared a draft above.*

**Any open questions / requests for help from the group?**

**Comment by gwenwindflower** [comment]
closing this for now, can be reopened as a discussion or issue in the docs repo if there are further developments
