### ISSUE TITLE
Model Naming Conventions Part 2

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#68]
**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
[Part 1](https://docs.getdbt.com/blog/on-the-importance-of-naming)
**Link to notes / outline / draft:**
[Draft](https://docs.google.com/document/d/1_Jlp1KJOHWxvodNKp4SUWDIf2zBrXUqPhAWhkMfYyb4/edit)

**Comment by jasnonaz** [comment]
@patkearns10 this is great - there is such a density of information here.

I've been thinking about the structure of your naming series and how it flow, I want to run something by you.

The first part of this on 5S is excellent, but I'm not sure it fits into the overall story you're trying to tell with the naming conventions post. I think we pop that out and have it be a standalone (or a _bonus_ at the end of the mainline series).

I think it's probably worth us spending a little time thinking through the overall structure of this series. How does this read to you?

Part 1: On the Importance of Naming [published]
Part 2: Signs of a well organized project and a high level abstrction on model types (explaining the colors in the diagram) 
![image](https://user-images.githubusercontent.com/8147311/149050388-35c31e3b-98b1-4fe4-b4d0-69b93ade200d.png)
Part 3: Source and Staging Models
Part 4: Marts
Part 5: Beyond Marts
Part Bonus: Applying 5S to your project organization

We've got all the building blocks we need for a truly epic series of posts just need to wrangle a little structure around them.

Does this structure work for you? If so we can get part 2 ready to pub for next week.

**Comment by patkearns10** [comment]
Yes - I think that makes sense to me - I was feeling iffy about the current order as well.  Okay, I'll do a once over of the new Part 2 and make sure it's all there.

**Comment by gwenwindflower** [comment]
i'm closing this for now and have made a note to discuss how we want to port this into the new repo
