### ISSUE TITLE
Staging Models - Best Practices

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#7]
Providing tangible tips for how to set up staging tables. Staging tables are one of the quickest ways to get value out of dbt and time invested in staging probably has the highest multiple of time saved elsewhere of any aspect of dbt

**Comment by lbenezra-FA** [comment]
is this cutie still looking for an author?

**Comment by gwenwindflower** [comment]
yis!

**Comment by gwenwindflower** [comment]
![FKs1g3vXMAAr7I9](https://user-images.githubusercontent.com/91998347/152437269-ac6750d2-77d5-4c96-9475-acba164a0306.jpeg)
this could be u if u write this article

**Comment by lbenezra-FA** [comment]
i'd LOVE to be this post's opossum mom!

**Comment by gwenwindflower** [comment]
sold! i will be possum #2, your trusty editor

**Comment by lbenezra-FA** [comment]
wooooooo!!! ty ty! team trash forevz!

**Comment by gwenwindflower** [comment]
closed and moved here https://github.com/dbt-labs/docs.getdbt.com/discussions/1148
