### ISSUE TITLE
Change data capture on metrics in dbt

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-technical-blog-writing#70]
**What's your key point?**
How to capture version history of a dbt model with both:
a) changing source data
b) changing business logic

Outline solution(s) and the pros/cons & use cases of them.

Current solution ideas:
- Downstream Incremental Models
- Upstream Snapshots

**Prior art:**
Let me know if you've read any prior writing on this topic!

**Link to notes / outline / draft:**
I have a very rough writeup in the ProServ knowledge repo, but will share a link to a google doc when I've created an outline!

**Estimated first draft date:**
TBD

**Comment by graciegoheen** [comment]
Got started on a draft today!

Google Doc here: [Capturing Version History in dbt](https://docs.google.com/document/d/17ySaGWeRi8ggVwKtK0sXu2vEL_jgB2_iprrya7MCYfM/edit?usp=sharing)

**Comment by krevitt** [comment]
Modified the title here based on office hours discussion!  And a few notes from that convo [are here in notion](https://www.notion.so/dbtlabs/devhub-Office-Hours-2021-1-6-a8b21b1181ae4ae0b26158de96c43a01#7b5f9665bf30463db1a4e5eda43ace35).

**Comment by gwenwindflower** [comment]
transferred here https://github.com/dbt-labs/docs.getdbt.com/discussions/1144
