### ISSUE TITLE
Our Thoughts: Branching Strategies

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-technical-blog-writing#71]
**What's your key point?**
What are dbt's opinions on setting up a git workflow / deciding a branching strategy (especially when you have a development environment that is unique from your testing environment)?

**Prior art:**
This will potentially be related to [Amy Chen's](https://github.com/dbt-labs/dbt-technical-blog-writing/issues/43) upcoming devhub post. 

**Link to notes / outline / draft:**
I have a very rough writeup in the ProServ knowledge repo, but will share a link to a google doc when I've created an outline!

**Estimated first draft date:**
TBD

**Comment by amychen1776** [comment]
@graciegoheen I'm so intrigued to read this! I do touch upon it a little in my rough draft ([here if you want to take a look](https://docs.google.com/document/d/1CDcO_8vKs9KfDtn1lJ5vFw2xqxGB7hq5Jmbd3C5PbQE/edit)) but don't get very in-depth outside of offering the options

**Comment by gwenwindflower** [comment]
i do think this is related to the environments work that amy has worked on and can be followed up with as a companion to that, so going to retire this with the repo for now and we'll see how it resurfaces in relation to that guide.
