### ISSUE TITLE
Founding an Analytics Engineering Team

### ISSUE THREAD

**Issue by natesooter** [dbt-labs/dbt-technical-blog-writing#76]
**What's your key point?**

- What the creation of an analytics engineering team from scratch looks like, with dbt as a core component

**Prior art:**

- [This Twitter thread will be the starting point for the post.](https://twitter.com/NateSooter/status/1472968046910132225?s=20)

**Link to notes / outline / draft:**

- See above response. I'm open to discussing this a bit more about focusing the discussion / changing it around to make it more 'dbt-ized'. So the outline may materially change from the Twitter thread.

**Estimated first draft date:**

- 1/16, though may be earlier depending on discussion of how changed the outline is through discussion

**Any open questions / requests for help from the group?**

- Would be interested in initial feedback on editing/reformatting/etc the Twitter thread into something more appropriate for your blog.

**Comment by natesooter** [comment]
[Here's the link](https://docs.google.com/document/d/1xtarVNy5kRjNJmd-zKkCWyqTA9VNRd_FjSOC21KQDVo/edit?usp=sharing) to the Google Doc of the blog post. Goal is to complete by 1/23.

**Comment by natesooter** [comment]
@jasnonaz Have 2/3rds of this written, but forgot that this weekend is my first one at home with two kids without my wife, so writing a blog is definitely not going to happen!  Should have it done within the next week though.

**Comment by natesooter** [comment]
@jasnonaz I've completed my initial draft & gone through it for grammar & general readability.

It's ready now for your review.  Once we go through any recommended revisions, the next step will be to share with the Smartsheet PR team for final review before it can be published.  Once you're good with it and Smartsheet PR is good with it, we can greenlight to publish.

**Comment by jasnonaz** [comment]
Fantastic - thank you Nate!! We'll take a look and get thoughts back to you by Wednesday EOD. So excited to get this out into the world.

**Comment by jasnonaz** [comment]
Nate - this post is incredible. Thank you so much for sharing the journey that your team went on to make analytics engineering a reality at Smartsheet. It's just so valuable for folks to be able to hear these stories (and hopefully fun / cathartic for you to put this together).

I added a couple extremely minor edits but I think that your instincts in how to tell this story were spot on. Would love to get this over to PR for approval so that we can get this live.

**Comment by natesooter** [comment]
Thank you Jason!  I appreciate the opportunity to write it up & can't wait to see what the data community thinks.  I'll get this over to my PR team & will update as soon as it's given the stamp of approval for publishing.

**Comment by natesooter** [comment]
@jasnonaz As an update, the PR team needs one more person look the blog over. I'll update you as soon as it's greenlighted for publishing. Almost there!

**Comment by natesooter** [comment]
@jasnonaz Happy Friday and apologies for the delay.  The good news: I have conditional green light after making a few edits.  I should have those done by end of day tomorrow.  I will confirm for you when the edits are done, you can take another look through to confirm things look good on your end & we can then move forward with publishing.

So, one more day or so and I'll reply back with the green light from our end!

**Comment by natesooter** [comment]
@jasnonaz This is complete - I've made the minor edits per the request of my internal PR team.

So, this is the official **green light** to post!  I'm immensely excited to see this go live.

**Comment by gwenwindflower** [comment]
fantastic! @natesooter i'm closing this issue a bit early as we've consolidated our devblog system into our main documentation repo but excited to get this published asap!
