### ISSUE TITLE
Auditing Techniques for Refactoring

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-technical-blog-writing#77]
**What's your key point?**
How to audit as you edit/refactor using audit-helper-package in-line, to avoid having an intense round of editing at the end of a long sprint
or
How to use audit-helper-package as you refactor to avoid having an intense round of testing at the end of a long sprint

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
- works with [refactoring queries course ](https://courses.getdbt.com/courses/refactoring-sql-for-modularity) & [Christine's post](https://blog.getdbt.com/sql-refactoring-course/)

**Link to notes / outline / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
https://www.notion.so/dbtlabs/Editing-Auditing-WIP-4da3840939b249b1b6a4f32fdc5a85fa
https://docs.google.com/document/d/1diM3wKREFqvOCDt-6q-yK7-UabScNdBI3oQdp5fenOM/edit

**Estimated first draft date:**
*Leave blank if you already shared a draft above.*

**Any open questions / requests for help from the group?**

**Comment by gwenwindflower** [comment]
closing this one for now and will discussion with DX how to port to new repo
