### ISSUE TITLE
Deduping your dupes!

### ISSUE THREAD

**Issue by lbenezra-FA** [dbt-labs/dbt-technical-blog-writing#78]
**What's your key point?**
This is a preface to the [Joining Snapshots](https://docs.google.com/document/d/1xH82PG1d28Fv5jwCY9WENW-3ERxjNUMSK5LLwIvfYz0/edit#heading=h.4fgstn7n2kr5) blog post, which requires data to be dupe-free in order for the join logic to work. 

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
not that I know of!

**Link to notes / outline / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
[How-to: dedupe your dupes!](https://docs.google.com/document/d/18QB1otduteheSYIHLWa63Mw9fhEpMX_p1FktfYV4oMw/edit?usp=sharing)

**Estimated first draft date:**
*Leave blank if you already shared a draft above.*

**Any open questions / requests for help from the group?**

**Comment by jasnonaz** [comment]
Hi Lauren - this piece is great!! Couple notes:
- Can we introduce both:
  - What exactly we mean by duplicates? How might someone identify them sentantically / conceptually before we start thinking about how to find them in code? Are there different types of duplicates (ie can they just be idenfied by looking at the Primary Key? When does this work vs. not work?
  - What are the the reason that people might want to look for duplicates in their code?

- I'm trying to understand how much this post expects you to be working off of snapshot data / what expectations it has for the data you're looking at. I know we pulled this out of a snapshot post - just trying to determine the contours of the post here. Can we spell that out a little more explicitly?

Once we get those in there I think we're good to go with this and then getting the larger snapshot post out the door.

**Comment by gwenwindflower** [comment]
closed to transfer here https://github.com/dbt-labs/docs.getdbt.com/discussions/1141
