### ISSUE TITLE
Long term fix for an "under-documented" and "under-tested" dbt project

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-technical-blog-writing#80]
Some projects don't start with good practices on which models/columns should be documented and tested. After a while it can become a huge effort to fix it and the bad state may re-appear

In my mind the fix needs to happen in 2 parts:
1. find the current models that should be documented/with tests. 
    - Decide what needs to be documented/tested (opinionated)
    - Document/test the models that are lacking such information. This can be done manually in YAML (potentially time consuming and error prone) or using the tool [Tangata](https://github.com/ciejer/tangata_local) created by Chris Jenkins
2. Setup automated tests to prevent the rules to be broken, for example leveraging [pre-commit hooks](https://github.com/offbi/pre-commit-dbt)

**Prior art:**
- demo of tangata at Coalsece: https://coalesce.getdbt.com/talks/sharing-the-knowledge-joining-dbt-and-the-business-using-tangata/

**Link to notes / outline / draft:**
[Internal to dbt Labs](https://docs.google.com/document/d/1b1fQWzWUUHLggtTix3TaS9HnVxUMfp5QVRt2TTPPcPE/edit#)

**Estimated first draft date:**
02/10/2022

**Any open questions / requests for help from the group?**

**Comment by jasnonaz** [comment]
Fantastic post idea @b-per - looking forward to reading!

**Comment by b-per** [comment]
I updated the issue with a link to the draft for the article.

**Comment by gwenwindflower** [comment]
closing this and moving to the docs repo where we are centralizing this work -- we can pick up the convo there -- looks great from a quick scan @b-per excited! https://github.com/dbt-labs/docs.getdbt.com/discussions/1138
