### ISSUE TITLE
Hiring an analytics engineer

### ISSUE THREAD

**Issue by gwenwindflower** [dbt-labs/dbt-technical-blog-writing#83]
**What's your key point?**

We have guidance for clients on hiring an AE, let's publish it 

**Prior art:**
https://www.notion.so/dbtlabs/Hiring-Guidance-Analytics-Engineer-Technical-Data-Analyst-Senior-Analyst-70ce58791e3248d3a35db668463eed24

**Comment by krevitt** [comment]
FYI we also have [this old post](https://www.getdbt.com/data-teams/hiring-analytics-engineer/) (ranks #1 for "hiring an analytics engineer") from Janessa + Erin - so we may want to focus on some specific technical aspect (like interview questions, test project, etc).

**Comment by gwenwindflower** [comment]
closing in favor of docs discussion https://github.com/dbt-labs/docs.getdbt.com/discussions/1134
