### ISSUE TITLE
[NEW] Embedded {analysts|designers|etc} vs specialists in a centralised team 

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-technical-blog-writing#84]
**What's your key point?**
[Tristan](https://docs.google.com/document/d/17NHxkZw4MAWje5JuYbERhLPi5pK0IUxzyyjjJbXluQI/edit#) and [Janessa](https://www.notion.so/dbtlabs/A-few-rough-notes-on-embedded-roles-ea81bb0f3f2a4c88b320f8a0a95b45b2) have both written great stuff on this - can we jazz it up, combine the concepts, and put it out for the world to see?

**Prior art:**
☝️

**Comment by jasnonaz** [comment]
Great idea! You interested in writing this or should we throw the "Looking for author" tag on?

**Comment by joellabes** [comment]
Happy for it to get a looking for author tag; maybe I'll wind up coming free but let's not have me as a blocker in the meantime!

**Comment by gwenwindflower** [comment]
i think we have enough other ideas cooking in the new repo i'm not going to port this one
