### ISSUE TITLE
What is a DAG and Why is it Important?

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt-technical-blog-writing#86]
**What's your key point?**
This is an incredibly important concept that we frequently want to link to and don't have a dedicated post for already
**Prior art:**[
Christine's excellent post on modular data modeling](https://www.getdbt.com/analytics-engineering/modular-data-modeling-technique/) - hoping for something with a lot of the same insights as this but focused on a short explanation of what dags are and how they are used
**Link to notes / outline / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*

**Estimated first draft date:**
*Leave blank if you already shared a draft above.*

**Any open questions / requests for help from the group?**

**Comment by gwenwindflower** [comment]
i think this should be tackled as a glossary entry, closing for now but feel free to open as a fresh discussion if you disagree!
