### ISSUE TITLE
Building a feature store with dbt

### ISSUE THREAD

**Issue by burkaygur** [dbt-labs/dbt-technical-blog-writing#88]
**What's your key point?**
With fal feature store (which is built as a [dbt package](https://github.com/fal-ai/dbt_feature_store)), you can have a very solid set up for tabular ML model workflows right within your dbt project.

**Prior art:**
*Any other posts that exist on this topic (here or elsewhere).*
#72 talks about the baton pass between analytics engineering and ML, mentions fal.
https://github.com/fal-ai/fal/issues/91 talks about the design process of the dbt package.

**Link to notes / outline / draft:**
*Google docs preferred, please set sharing to `anyone with the link can view`.*
Draft coming soon.

**Estimated first draft date:**
2/17/22 EOD

**Any open questions / requests for help from the group?**
Would appreciate reviews!

**Comment by gwenwindflower** [comment]
hey @burkaygur, we love this idea! dbt for modeling with fal, Continual.ai, or more hand rolled processes is something we want to lean into in a couple months. we have some foundational work we'd like to knock out first, so we probably wouldn't publish this for awhile though, just a heads up. 

more urgently -- we're shutting down these repo and moving this into Discussions + Issues with the dbt Docs repo. along with that new system, we're creating a new outlining system for folks to use before they write drafts. 

i'm going to close this issue and link it to a shared discussion for dbt + ML that you'll be tagged in, and once our new system is up and running we'll let you know and we can start moving this through that.

thanks again for spiking this out and excited to develop this with you in coming months!

**Comment by gwenwindflower** [comment]
here's the discussion https://github.com/dbt-labs/docs.getdbt.com/discussions/1158

**Comment by burkaygur** [comment]
Sounds great. We will check back in a month. In the meantime, we are working on the draft and will share it then.
